### ISSUE TITLE
Syntax error in getting started guide code example

### ISSUE THREAD

**Issue by IRLeif** [danschultzer/pow_assent#7]
In the getting started guide, there is this code example:

```elixir
defmodule MyApp.Users.User
  use Ecto.Schema
  use Pow.Ecto.Schema
  use PowAssent.Ecto.Schema

  schema "users" do
    has_many :user_identities,
      MyApp.UserIdentities.UserIdentity,
      on_delete: :delete_all

    # ...
  end

  # ..
end
```

Cuasing this error during compilation:

```
$ mix
warning: found quoted keyword "test" but the quotes are not required. Note that keywords are always atoms, even when quoted, and quotes should only be used to introduce keywords with foreign characters in them
  mix.exs:58

Compiling 2 files (.ex)

== Compilation error in file lib/my_app/users/user.ex ==
** (SyntaxError) lib/my_app/users/user.ex:11: unexpected token: end
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

I believe this example is missing a do and should look like this:

```elixir
defmodule MyApp.Users.User do # Missing do keyword added here
  use Ecto.Schema
  use Pow.Ecto.Schema
  use PowAssent.Ecto.Schema

  schema "users" do
    has_many :user_identities,
      MyApp.UserIdentities.UserIdentity,
      on_delete: :delete_all

    # ...
  end

  # ..
end
```

**Comment by danschultzer** [comment]
Thanks 😄 I've fixed this in the readme, and updated with the required Pow set up step too (#6) so you can get started.
